title: Great web agency
email: omau.paav@gmail.com
description: "Hola mama estoy en internet."
baseurl: "http://mewsic156.github.io/website/"
url: "http://mewsic156.github.io/website/"
# twitter_username: jekyllrb
# github_username:  jekyll
plugins:
  - jekyll-feed
permalink: none
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Mauricio Palau"
      category: "Technical Writing"


