title: Mauricio Palau
email: ""
description: "My Portfolio Website"
baseurl: ""
url: "https://mauriciopalau.com/"
# twitter_username: jekyllrb
# github_username:  jekyll
plugins:
  - jekyll-feed
permalink: none
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Mauricio Palau"
      category: "Technical Writing"


