- icon: "ion-android-document"
  title: "Technical Documentation"
  content: "Produce user-friendly manuals and guides for clear understanding."

- icon: "ion-android-laptop"
  title: "API Documentation"
  content: "Create detailed guides to help developers seamlessly integrate software."

- icon: "ion-android-create"
  title: "Writing and Editing"
  content: "Write clear and precise technical content suitable for diverse audiences."

- icon: "ion-android-clipboard"
  title: "Content Strategy"
  content: "Develop strategies for consistent and lifecycle-aligned updates to documentation."

- icon: "ion-chatbox-working"
  title: "User Experience Writing"
  content: "Enhance software usability with clear user interface text."

- icon: "ion-android-map"
  title: "Information Architecture"
  content: "Organize content to ensure efficient usability and information retrieval."

- icon: "ion-android-bookmark"
  title: "Knowledge Management"
  content: "Implement systems for organized and accessible documentation."

- icon: "ion-videocamera"
  title: "Training and Support Materials"
  content: "Develop resources such as tutorials and articles for effective user training and support."
