- icon: "ion-android-document"
  title: "Manuals and Guides"
  content: "Aid users in using software products and services."

- icon: "ion-android-laptop"
  title: "API Documentation"
  content: "Aid developers in integrating and utilizing APIs effectively."

- icon: "ion-android-create"
  title: "Copywriting"
  content: "Engage and persuade users through compelling written content."

- icon: "ion-android-clipboard"
  title: "Content Strategy"
  content: "Implement strategies for consistent updates to documentation."

- icon: "ion-chatbox-working"
  title: "User Experience Writing"
  content: "Enhance software usability with clear user interface text."

- icon: "ion-android-map"
  title: "Information Architecture"
  content: "Organize content to ensure efficient information retrieval."

- icon: "ion-android-bookmark"
  title: "Knowledge Management"
  content: "Implement systems to manage and facilitate access to content."

- icon: "ion-videocamera"
  title: "Training and Support Materials"
  content: "Support users with tutorials and articles for training and support."
